// Below code belongs to promise 
// const myPromise = new Promise((resolve, reject) => {
//     let a = false;
//     setTimeout(() => {
//       return (a) ? resolve('Successful promise is fulfilled'): reject('Promise is failure');
//     }, 300);
//   }); 
  
//   myPromise
//   .then(value => { console.log(value) })
//   .catch(err => { console.log(err) });
  

// const myPromise=new Promise((resolve,reject)=>{
//     let a=true;

//     setTimeout(()=>{
//         return (a)?resolve("Promise is Successful"):reject("Promise is failure");
//     })
// })

// myPromise
// .then(value=>{console.log(value)})
// .catch(err=>{console.log(err)})

//************************************************************************************************************************************** */

